name: GitHub-Profile-3D-Contrib

on:
  schedule: # 00:00 KST == 15:00 UTC
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_3D_CONTRIB }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name Jiseoup
          git config user.email jseoup@gmail.com
          git add -A .
          git commit -m "generated"
          git push
